theme: jekyll-theme-architect
title: Bucket List API by Krishna Pankhania
description: This api provides various suggestions of activities to do,places to visit for your bucket. Feel free to use this api for you demo projects
